# Site settings
title: Havaianas Summer Escapes
client:
  name: Havaianas
  link: "https://www.havaianas-store.com/en?cCode=GB&utm_source=20&utm_term=ext2&utm_content=display&utm_campaign=cont_"
core-se-link: https://www.secretescapes.com/current-sales

description: >
  Explore the world this summer with a pair of Havaianas on your feet. Havaianas and Secret Escapes bring you the summer escapes collection, with handpicked travel offers that will leave you reeling with that sunshine feeling.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/havaianas" # the subpath of your site, e.g. /blog/
img:     "/havaianas/_assets/img"
css:     "/havaianas/_assets/css"
js:      "/havaianas/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed