

###############################################################
##  CITY  //  category:city
##-------------------------------------------------------------


- id: sandals-1
  category: city
  title: You Belize
  description: Product description
  price: 99
  link:

- id: sandals-2
  category: city
  title: You St Tropez
  description: Product description
  price: 99
  link:

- id: sandals-3
  category: city
  title: You Riviera Maxi
  description: Product description
  price: 99
  link:

- id: sandals-4
  category: city
  title: You Belize
  description: Product description
  price: 99
  link:

- id: sandals-5
  category: city
  title: You Riviera
  description: Product description
  price: 99
  link:

- id: sandals-6
  category: city
  title: You Metallic
  description: Product description
  price: 99
  link:


###############################################################
##  TROPICAL  //  category:tropical
##-------------------------------------------------------------


- id: flip-flops-1
  category: tropical
  title: Slim
  description: Product description
  price: 99
  link:

- id: flip-flops-2
  category: tropical
  title: Slim Tropical
  description: Product description
  price: 99
  link:

- id: flip-flops-3
  category: tropical
  title: Slim
  description: Product description
  price: 99
  link:

- id: flip-flops-4
  category: tropical
  title: Slim
  description: Product description
  price: 99
  link:

- id: flip-flops-5
  category: tropical
  title: Slim Tropical
  description: Product description
  price: 99
  link:

- id: flip-flops-6
  category: tropical
  title: Slim
  description: Product description
  price: 99
  link:


###############################################################
##  ADVENTURE  //  category:adventure
##-------------------------------------------------------------


- id: espadrilles-1
  category: adventure
  title: Origine Flatform Fashion
  description: Product description
  price: 99
  link:

- id: espadrilles-2
  category: adventure
  title: Origine III
  description: Product description
  price: 99
  link:

- id: espadrilles-3
  category: adventure
  title: Origine Flat Form Up
  description: Beige
  price: 99
  link:

- id: espadrilles-4
  category: adventure
  title: Origine Flatform Fashion
  description: Product description
  price: 99
  link:

- id: espadrilles-5
  category: adventure
  title: Origine Slim
  description: Product description
  price: 99
  link:

- id: espadrilles-6
  category: adventure
  title: Origine Flat Form Up
  description: Black
  price: 99
  link:


